app.factory('filterTags', function () {
  var foodlist = [
    'apple',
    'avocado',
    'banana',
    'blackberry',
    'blueberry',
    'cucumber',
    'cherry',
    'coconut',
    'cranberry',
    'dragonfruit',
    'durian',
    'grape',
    'grapefruit',
    'guava',
    'kiwi fruit',
    'lemon',
    'lime',
    'mango',
    'melon',
    'honeydew',
    'watermelon',
    'olive',
    'orange',
    'clementine',
    'mandarine',
    'papaya',
    'peach',
    'pear',
    'plum',
    'pineapple',
    'pumpkin',
    'pomegranate',
    'raspberry',
    'strawberry',
    'artichoke',
    'asparagus',
    'aubergine',
    'amaranth',
    'legumes',
    'bean sprouts',
    'black beans',
    'black-eyed peas',
    'broad beans',
    'chickpeas',
    'green beans',
    'kidney beans',
    'lentils',
    'lima beans',
    'butter bean',
    'mung beans',
    'split peas',
    'soy beans',
    'peas',
    'mangetout',
    'snap peas',
    'bok choy',
    'broccoflower',
    'broccoli',
    'brussels sprouts',
    'cabbage',
    'cannabis',
    'carrots',
    'cauliflower',
    'celery',
    'corn salad',
    'frisee',
    'herbs',
    'spices',
    'anise',
    'basil',
    'caraway',
    'cilantro seeds',
    'coriander',
    'chamomile',
    'dill',
    'fennel',
    'lavender',
    'lemon grass',
    'marjoram',
    'oregano',
    'parsley',
    'rosemary',
    'sage',
    'thyme',
    'kale',
    'lettuce',
    'maize',
    'corn',
    'sweetcorn',
    'mushrooms',
    'mustard greens',
    'nettles',
    'chives',
    'garlic',
    'onion',
    'shallot',
    'spring onion',
    'green onion',
    'scallion',
    'parsley',
    'pepper',
    'green pepper',
    'red pepper',
    'bell pepper',
    'pimento',
    'chili pepper',
    'capsicum',
    'jalape?o',
    'jalepeno',
    'habanero',
    'paprika',
    'tabasco pepper',
    'cayenne pepper',
    'rhubarb',
    'beetroot',
    'beet',
    'carrot',
    'celeriac',
    'daikon',
    'ginger',
    'parsnip',
    'radish',
    'turnip',
    'wasabi',
    'horseradish',
    'white radish',
    'salsify',
    'oyster',
    'spinach',
    'squash',
    'courgette',
    'cucumber',
    'squash',
    'pumpkin',
    'tomato',
    'potato',
    'sweet potato',
    'taro',
    'yam',
    'watercress',
    'zucchini',
    'lentil',
    'beef',
    'chicken',
    'sheep',
    'mutton',
    'pork',
    'rabbit',
    'steak',
    'veal',
    'duck'
  ];
  return {
    filterArray: function (oldArray) {
      var searchKeys = "";
      var tags = oldArray.filter(function (file) {
        var token;
        foodItems.forEach(function (item) {
          if (file === item)
            token = item;
        });
        return file === token;
      });
      tags.forEach(function (file, index) {
        searchKeys += file.toString();
        if (index !== tags.length-1)
          searchKeys += '+';
      });
      return searchKeys;
    }
  };
});
